# server: RTX4000 * 4
# basic
net: "ResAttNet_OneLoss"
dataset: "SHHS1"
freq: 125
CUDA_VISIBLE_DEVICES: "0,1,2,3"

# paths
path: 
  weights: "./weights_server"
  tblogs: "./logs/server"
  log: "./history/log_server.txt"
redir_root: false
redir_cache: false

# training utils
resume: false
resume_ckp: "./weights/checkpoint_"
train_parallel: true
train_thread: 8
# test utils
eval_parallel: true
eval_thread: 8

# training params
EPOCH_MAX: 21
EPOCH_STEP: 7000
BATCH_SIZE: 200
LR: 0.001
scheduler: "torch.optim.lr_scheduler.MultiStepLR(optim, [14], .1)" 
# test params
tvt: "test"
test_dataset: "SHHS1"
best_ckp: "./weights_all/epoch_21_val_loss=0.324118_acc=0.8900"