# server: RTX4000 * 4
# basic
net: "ResAttNet"
#dataset: ["SHHS1", "SHHS2", "CCSHS", "SOF", "CFS", "MROS1", "MROS2"]
dataset: ["SHHS1", "SHHS2", "CCSHS", "SOF", "CFS", "MROS1"]
freq: 125
CUDA_VISIBLE_DEVICES: "0,1,2,3"

# paths
path: 
  weights: "./weights_leave_mros2"
  tblogs: "./logs_leave_mros2"
  log: "./history/log_leave_mros2.txt"
redir_root: false
redir_cache: false

# training utils
resume: false
resume_ckp: "./weights/checkpoint_"
train_parallel: true
train_thread: 14 
# test utils                   
eval_parallel: true
eval_thread: 12

# training params
EPOCH_MAX: 20
EPOCH_STEP: 7000
BATCH_SIZE: 200
LR: 0.001
scheduler: "torch.optim.lr_scheduler.MultiStepLR(optim, [14], .1)" 
# test params (tvt = test or all)
tvt: "all"
test_dataset: "MROS2"
best_ckp: "weights_leave_mros2/epoch_20_val_loss=0.338751_acc=0.8864"